DROP FUNCTION IF EXISTS uuid_to_bin;

CREATE FUNCTION IF NOT EXISTS uuid_to_bin(
    s CHAR(36)
) RETURNS binary(16)
    DETERMINISTIC
RETURN UNHEX(CONCAT(LEFT(s, 8), MID(s, 10, 4), MID(s, 15, 4), MID(s, 20, 4), RIGHT(s, 12)));

DROP FUNCTION IF EXISTS bin_to_uuid;

DELIMITER //
CREATE FUNCTION IF NOT EXISTS bin_to_uuid(b BINARY(16)) RETURNS char(36) CHARSET utf8
    DETERMINISTIC
BEGIN
    DECLARE HEX CHAR(32);
    SET HEX = HEX(b);
    RETURN LOWER(CONCAT(LEFT(HEX, 8), '-', MID(HEX, 9,4), '-', MID(HEX, 13,4), '-', MID(HEX, 17,4), '-', RIGHT(HEX, 12)));
END//
DELIMITER ;
